# Generated by Django 2.2 on 2020-06-30 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='имя категории')),
                ('descript', models.TextField(blank=True, verbose_name='описание категории')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='имя игры')),
                ('image', models.ImageField(blank=True, upload_to='games_images')),
                ('short_desc', models.CharField(blank=True, max_length=64, verbose_name='краткое описание игры')),
                ('descript', models.TextField(blank=True, verbose_name='описание игры')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='цена игры')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='количество на складе')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.GameCategory', verbose_name='категория игры')),
            ],
        ),
    ]
